name: test-develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up Mysql
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE db_test' -u root -p root

    - name: Test
      env:
        ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
      run: go test -v ./...
